#!/usr/bin/perl -p

s/\b((\d[-_\.]?)+)\b/\e[35m$1\e[0m/gi;

s/\b((err(or)?s?|fail(i?ure)?s?):?)/\e[31;1m$1\e[0m/gi;

s/\b((success|good|pass):?)/\e[32;1m$1\e[0m/gi;

s/\b(warn(ings?):?)/\e[33;1m$1\e[0m/gi;

s/\b((info(rmation)?|notes?):?)/\e[34;1m$1\e[0m/gi;

s/\b((lines?|col(umn)?s?)\s?[:=#]?)/\e[36m$1\e[0m/gi;
